/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BTechCreditTransferRouteImport } from './routes/b-tech-credit-transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BTechCreditTransferRoute = BTechCreditTransferRouteImport.update({
  id: '/b-tech-credit-transfer',
  path: '/b-tech-credit-transfer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b-tech-credit-transfer': typeof BTechCreditTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b-tech-credit-transfer': typeof BTechCreditTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b-tech-credit-transfer': typeof BTechCreditTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b-tech-credit-transfer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b-tech-credit-transfer'
  id: '__root__' | '/' | '/b-tech-credit-transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BTechCreditTransferRoute: typeof BTechCreditTransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b-tech-credit-transfer': {
      id: '/b-tech-credit-transfer'
      path: '/b-tech-credit-transfer'
      fullPath: '/b-tech-credit-transfer'
      preLoaderRoute: typeof BTechCreditTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BTechCreditTransferRoute: BTechCreditTransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
